//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Pair<T, U> {
		public Pair() {
		}
		
		public Pair(T first, U second) {
			this.First = first;
			this.Second = second;
		}
		
		public T First { get; set; }
		public U Second { get; set; }
	};
}

