//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace AssemblyCSharp
{
	public class Room : MonoBehaviour
	{
		bool doorNorth = false;
		bool doorEast  = false;
		bool doorSouth = false;
		bool doorWest  = false;

		public Room ()
		{
			// TODO: instantiate a room object with a background image
		}

		public void addSourceDoor(FloorManager.Direction dir)
		{
			switch (dir)
			{
				case FloorManager.Direction.NORTH:
					doorNorth = true;
				break;
				case FloorManager.Direction.EAST:
					doorEast = true;
				break;
				case FloorManager.Direction.SOUTH:
					doorSouth = true;
				break;
				case FloorManager.Direction.WEST:
					doorWest = true;
				break;
			}
		}

		public void addUnexploredDoor(FloorManager.Direction dir)
		{
			switch (dir)
			{
				case FloorManager.Direction.NORTH:
					if(doorNorth)
					{
						addUnexploredDoor(dir+1);
						return;
					}
				    else
					{
						doorNorth = true;
						// TODO: instantiate a door
					}
				break;
				case FloorManager.Direction.EAST:
					if(doorEast)
					{
						addUnexploredDoor(dir+1);
						return;
					}
				    else
					{
						doorEast = true;
						// TODO: instantiate a door
					}
				break;
				case FloorManager.Direction.SOUTH:
					if(doorSouth)
					{
						addUnexploredDoor(dir+1);
						return;
					}
				    else
					{
						doorSouth = true;
						// TODO: instantiate a door
					}
				break;
				case FloorManager.Direction.WEST:
					if(doorWest)
					{
						addUnexploredDoor(dir+1);
						return;
					}
				    else
					{
						doorWest = true;
						// TODO: instantiate a door
					}
				break;
			}
		}

		public void generateWalls()
		{
			// TODO: Implement
			// TODO: Make sure to allow door access and not to layer walls over doors
		}

	}
}

